#!/usr/bin/env bash
# SessionStart hook: orient the agent automatically at the start of every session.
#
# Stdout from a SessionStart hook is injected into Claude's context, so this
# prints a compact briefing (branch, working-tree state, recent commits, and any
# in-flight long-task ledger) and quietly prepares the environment (npm install
# if node_modules is missing). Self-contained: bash + git + coreutils only.
#
# Hook protocol: exit 0 always — orientation must never block a session.
set -uo pipefail

cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0

echo "## Session briefing (auto-generated by session-start hook)"
echo

if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')"
  echo "- Branch: \`$branch\`"

  dirty="$(git status --porcelain 2>/dev/null | head -20)"
  if [ -n "$dirty" ]; then
    count="$(printf '%s\n' "$dirty" | wc -l | tr -d ' ')"
    echo "- Working tree: $count uncommitted change(s):"
    printf '%s\n' "$dirty" | sed 's/^/    /'
  else
    echo "- Working tree: clean"
  fi

  echo "- Recent commits:"
  git log --oneline -5 2>/dev/null | sed 's/^/    /'
fi

# Surface the long-task ledger so interrupted work resumes automatically.
ledger=".claude/state/TASKS.md"
if [ -f "$ledger" ] && grep -qE '^\s*- \[ \]' "$ledger" 2>/dev/null; then
  echo
  echo "### In-flight long task detected ($ledger)"
  echo "Open items below — continue them unless the user asks for something else:"
  grep -E '^\s*- \[.\]' "$ledger" | head -15 | sed 's/^/    /'
fi

# Prepare the toolchain in the background so lint/test/format work immediately.
if [ -f package.json ] && [ ! -d node_modules ] && command -v npm >/dev/null 2>&1; then
  echo
  echo "- Installing npm dependencies in the background (node_modules was missing)…"
  nohup npm install --no-audit --no-fund >/tmp/claude-npm-install.log 2>&1 &
fi

exit 0
