#!/usr/bin/env bash
# SessionStart フック: セッション開始時にエージェントへ自動で状況を伝える。
#
# SessionStart フックの stdout は Claude のコンテキストに注入されるため、
# ここでは簡潔なブリーフィング(ブランチ、ワーキングツリーの状態、直近の
# コミット、進行中の長期タスク台帳)を出力し、環境の準備(node_modules が
# 無ければ npm install)も静かに行う。依存は bash + git + coreutils のみ。
#
# ※ 出力は AI が読むため英語(言語ポリシーは CONTRIBUTING.md 参照)。
#
# フックプロトコル: 常に exit 0 — ブリーフィングがセッションを
# ブロックしてはならない。
set -uo pipefail

cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0

echo "## Session briefing (auto-generated by session-start hook)"
echo

if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')"
  echo "- Branch: \`$branch\`"

  dirty="$(git status --porcelain 2>/dev/null | head -20)"
  if [ -n "$dirty" ]; then
    count="$(printf '%s\n' "$dirty" | wc -l | tr -d ' ')"
    echo "- Working tree: $count uncommitted change(s):"
    printf '%s\n' "$dirty" | sed 's/^/    /'
  else
    echo "- Working tree: clean"
  fi

  echo "- Recent commits:"
  git log --oneline -5 2>/dev/null | sed 's/^/    /'
fi

# 長期タスク台帳を表示し、中断していた作業が自動で再開されるようにする。
ledger=".claude/state/TASKS.md"
if [ -f "$ledger" ] && grep -qE '^\s*- \[ \]' "$ledger" 2>/dev/null; then
  echo
  echo "### In-flight long task detected ($ledger)"
  echo "Open items below — continue them unless the user asks for something else:"
  grep -E '^\s*- \[.\]' "$ledger" | head -15 | sed 's/^/    /'
fi

# lint/test/format がすぐ使えるよう、ツールチェーンをバックグラウンドで準備。
if [ -f package.json ] && [ ! -d node_modules ] && command -v npm >/dev/null 2>&1; then
  echo
  echo "- Installing npm dependencies in the background (node_modules was missing)…"
  nohup npm install --no-audit --no-fund >/tmp/claude-npm-install.log 2>&1 &
fi

exit 0
